[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;essentiel"
newsButton = "ACTUS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actus.."
newsErrorFailedSpan = "Échec du chargement des actus"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actu"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "E-MAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "SE CONNECTER"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Ton mot de passe est envoyé directement à Mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter de nouveaux comptes ou gérer les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur au lancement."
launchDetachedTitle = "Lancer le processus du jeu séparé du launcher."
launchDetachedDesc = "Si le jeu n'est pas séparé, fermer le launcher fermera aussi le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Mods drop-in"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Packs de shaders"
shaderpackDesc = "Activer ou désactiver les shaders. Attention, les shaders ne tourneront correctement que sur des configs puissantes. Tu peux ajouter des packs personnalisés ici."
selectShaderpack = "Sélectionner un pack de shaders"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "Le minimum recommandé est de 3 gigaoctets de RAM. Mettre les valeurs minimum et maximum identiques peut réduire les lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l'exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'exécutable Java est validé avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options à fournir à la JVM à l'exécution. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas être inclus."
launcherTabHeaderText = "Paramètres du launcher"
launcherTabHeaderDesc = "Options liées au launcher lui-même."
allowPrereleaseTitle = "Autoriser les mises à jour pré-release."
allowPrereleaseDesc = "Les pré-releases incluent de nouvelles fonctionnalités qui peuvent ne pas avoir été totalement testées ou intégrées.<br>Cela sera toujours vrai si tu utilises une version pré-release."
dataDirectoryTitle = "Dossier de données"
selectDataDirectory = "Sélectionner le dossier de données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations locales de Java seront stockés dans le dossier de données.<br>Les captures d'écran et les sauvegardes de mondes sont stockées dans le dossier d'instance correspondant à la configuration du serveur."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Voir les infos et les notes de version de la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = ""
support = "Contacter le support"
devToolsConsole = ""
releaseNotes = "Notes de version"
changelog = "Journal des changements"
noReleaseNotes = "Aucune note de version"
viewReleaseNotes = ""
launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer et consulter les mises à jour du launcher."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Quoi de neuf"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En attente du client.."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "SE CONNECTER"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue pendant la connexion"
desc = "Une erreur inconnue est survenue. Consulte la console pour les détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter.."
failureTitle = "Erreur pendant le lancement"
failureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des infos système.."
noCompatibleJava = "Aucune installation<br>Java compatible trouvée"
installJavaMessage = "Pour lancer Minecraft, tu as besoin d'une installation 64 bits de Java {major}. Tu veux qu'on en installe une copie ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java.."
javaDownloadFailureTitle = "Erreur pendant le téléchargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java est requis<br>pour lancer"
javaRequiredMessage = 'Une installation x64 valide de Java {major} est requise pour lancer.<br><br>Réfère-toi à notre <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">guide de gestion Java</a> pour les instructions d’installation manuelle de Java.'
javaRequiredDismiss = "J'ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver une distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé a un mauvais hash, le fichier est peut-être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations du serveur.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l’index de distribution. Voir la console (CTRL + Shift + i) pour plus de détails."
pleaseWait = "Veuillez patienter.."
errorDuringLaunchTitle = "Erreur pendant le lancement"
seeConsoleForDetails = "Voir la console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Validation de l’intégrité des fichiers.."
errorDuringFileVerificationTitle = "Erreur pendant la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers.."
errorDuringFileDownloadTitle = "Erreur pendant le téléchargement des fichiers"
preparingToLaunch = "Préparation du lancement.."
launchingGame = "Lancement du jeu.."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n’a pas été téléchargé correctement. Résultat : le jeu ne peut pas se lancer.<br><br>Pour corriger ce problème, désactive temporairement ton antivirus et relance le jeu.<br><br>Si tu as le temps, merci de <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">signaler un ticket</a> en précisant quel antivirus tu utilises. On les contactera pour essayer de régler ça."
doneEnjoyServer = "Terminé. Profite du serveur !"
checkConsoleForDetails = "Merci de vérifier la console (CTRL + Shift + i) pour plus de détails."

[js.landing.news]
checking = "Vérification des actus"

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "Cap sur Westeros !"
joined = "Exploration du Royaume !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Quelque chose s'est mal passé"
errorMessage = "L’authentification Microsoft a échoué. Réessaie."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Quelque chose s'est mal passé"
errorMessage = "La déconnexion Microsoft a échoué. Réessaie."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner un compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>C'est ton dernier compte"
lastAccountWarningMessage = "Pour utiliser le launcher, tu dois être connecté à au moins un compte. Tu devras te reconnecter après.<br><br>Tu es sûr de vouloir te déconnecter ?"
confirmButton = "Oui, je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner un compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Retirer"
deleteFailedTitle = "Échec de suppression<br>du mod drop-in {fullName}"
deleteFailedMessage = "Vérifie que le fichier n'est pas utilisé et réessaie."
failedToggleTitle = "Échec d’activation/désactivation<br>d’un ou plusieurs mods drop-in"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Nécessite Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-release"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Échec du chargement des notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle pré-release disponible"
downloadingButton = "Téléchargement.."
downloadButton = 'Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Ferme le launcher et lance le dmg pour mettre à jour.</span>'
latestVersionTitle = "Tu utilises la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification des mises à jour.."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Impossible d’authentifier ton compte Microsoft. Réessaie."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : impossible de charger l’index de distribution"
fatalErrorMessage = "Impossible d’établir une connexion à nos serveurs pour télécharger l’index de distribution. Aucune copie locale n’était disponible. <br><br>L’index de distribution est un fichier essentiel qui fournit les dernières infos serveur. Le launcher ne peut pas démarrer sans. Assure-toi d’être connecté à internet et relance l’application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de l’actualisation de la connexion"
failedMessage = "Impossible d’actualiser la connexion pour <strong>{account}</strong>. Sélectionne un autre compte ou reconnecte-toi."
failedMessageSelectAnotherAccount = "Impossible d’actualiser la connexion pour <strong>{account}</strong>. Reconnecte-toi."
loginButton = "Se connecter"
selectAnotherAccountButton = "Sélectionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur pendant la connexion :<br>Profil non configuré"
noProfileDesc = "Ton compte Microsoft n’a pas encore de profil Minecraft configuré. Si tu as récemment acheté le jeu ou l’as récupéré via Xbox Game Pass, tu dois configurer ton profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si tu n’as pas encore acheté le jeu, tu peux aussi le faire sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur pendant la connexion :<br>Aucun compte Xbox"
noXboxAccountDesc = "Ton compte Microsoft n’a aucun compte Xbox associé."
xblBannedTitle = "Erreur pendant la connexion :<br>Xbox Live indisponible"
xblBannedDesc = "Ton compte Microsoft vient d’un pays où Xbox Live n’est pas disponible ou est interdit."
under18Title = "Erreur pendant la connexion :<br>Autorisation parentale requise"
under18Desc = "Les comptes d’utilisateurs de moins de 18 ans doivent être ajoutés à une Famille par un adulte."
unknownTitle = "Erreur inconnue pendant la connexion"
unknownDesc = "Une erreur inconnue est survenue. Consulte la console pour les détails."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Merci de signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Introuvable"
notFoundDesc = "Le point de terminaison d’authentification est introuvable. Merci de signaler ce problème."
accountMigratedTitle = "Erreur pendant la connexion :<br>Compte migré"
accountMigratedDesc = "Tu as essayé de te connecter avec un compte migré. Réessaie en utilisant l’e-mail du compte comme nom d’utilisateur."
invalidCredentialsTitle = "Erreur pendant la connexion :<br>Identifiants invalides"
invalidCredentialsDesc = "L’e-mail ou le mot de passe saisi est incorrect. Réessaie."
tooManyAttemptsTitle = "Erreur pendant la connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Il y a eu trop de tentatives de connexion sur ce compte récemment. Réessaie plus tard."
invalidTokenTitle = "Erreur pendant la connexion :<br>Jeton invalide"
invalidTokenDesc = "Le jeton d’accès fourni est invalide."
tokenHasProfileTitle = "Erreur pendant la connexion :<br>Le jeton a un profil"
tokenHasProfileDesc = "Le jeton d’accès a déjà un profil assigné. La sélection de profils n’est pas encore implémentée."
credentialsMissingTitle = "Erreur pendant la connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Nom d’utilisateur/mot de passe non envoyé ou mot de passe de moins de 3 caractères."
invalidSaltVersionTitle = "Erreur pendant la connexion :<br>Version de sel invalide"
invalidSaltVersionDesc = "Version de sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de média non supporté"
unsupportedMediaTypeDesc = "Type de média non supporté. Merci de signaler cette erreur."
accountGoneTitle = "Erreur pendant la connexion :<br>Compte migré"
accountGoneDesc = "Le compte a été migré vers un compte Microsoft. Connecte-toi avec Microsoft."
unreachableTitle = "Erreur pendant la connexion :<br>Injoignable"
unreachableDesc = "Impossible de joindre les serveurs d’authentification. Assure-toi qu’ils sont en ligne et que tu es connecté à internet."
gameNotPurchasedTitle = "Erreur pendant la connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = "Le compte avec lequel tu essaies de te connecter n’a pas acheté Minecraft. Tu peux l’acheter sur <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erreur inconnue pendant la connexion"
unknownErrorDesc = "Une erreur inconnue est survenue. Consulte la console pour les détails."
